### ISSUE TITLE
Thắc mắc

### ISSUE THREAD

**Issue by hohvn** [rexey3s/sailsjs-who-is-millionaire-app#1]
Hi bạn,

Mình đang nghiên cứu về sailsjs, bạn có thể cho mình hỏi trong project này bạn config mongoDB ở đâu vậy.
Nếu như mình ko sử dụng mongoDB mà sử dụng mysql thì có thể được không ạ?
Cảm ơn bạn nhiều

**Comment by rexey3s** [comment]
Chào bạn,

File config của mongodb của mình nằm trong đường dẫn config/local.js 
về cách config bạn có thể xem ở tutorial này 
http://irlnathan.github.io/sailscasts/blog/2013/08/30/building-a-sails-application-ep10-changing-databases-to-mongodb-with-sails-adapters/

Do sailsjs sử dụng waterline ORM nên bạn hoàn toàn có thể sử dụng mysql được.
bạn của thể xem thêm ở đây
http://sailsjs.org/#/documentation/concepts/ORM

Thân,
Chương.

**Comment by hohvn** [comment]
Cảm ơn bạn rất nhiều.
Nhờ project của bạn mình đã kiểm soát đc sails framework.
Nhưng mình có 1 vài thắc mắc về xử lý đang chơi thì user refresh màn hình. Bạn có kinh nghiệm xử lý vụ này không? Nhất là với 1 game có khá nhiều trạng thái

**Comment by rexey3s** [comment]
Chào bạn,
Về việc xử lý trạng thái khi user refresh màn hình mình dùng socket.io tích hợp sẳn trong sailsjs
Bạn tham khảo thêm ở đây
-  http://sailsjs.org/#/documentation/reference/websockets/resourceful-pubsub

Mình ví dụ trường hợp sau:
-  Đồng hồ đếm giờ giai đoạn chọn người chơi chính mình cho server đếm lưu kết quả đếm vào mongodb rồi cho nó send tới tất cả user qua socket nên user lúc đó có refresh cũng không thay đổi dc thời gian
- code đếm giờ cho server : trong file / api / controllers / AdminController.js dòng 377 - 395 ( trong đó "room.first_quiz_time" là một field trong db mình dùng lưu thời gian đếm còn "Player.publishUpdate" mình dùng đồng bộ về client qua socket 
- code lấy thời gian từ server gửi về: trong file assets/linker/js/app.js hàm wait_for_main() dòng 116 bạn thấy message trùng với cái mình gửi trong "publishUpdate" client chỉ việc update lời thời gian thôi
  Bạn có thể tham khảo thêm cách sử dụng socket.io trong sailsjs trong link sau:
  http://irlnathan.github.io/sailscasts/blog/2013/10/10/building-a-sails-application-ep21-integrating-socket-dot-io-and-sails-with-custom-controller-actions-using-real-time-model-events/
- Còn các vấn đề về các quyền trợ giúp, trả lời câu hỏi khi sử dụng xong mình cũng lưu lại trong database nên user có refresh hay nhấn lần nữa cũng không sử dụng lại dc bạn tham khảo trong các hàm "first_quiz_submit", "5050", "audience_support" trong file /api/controllers/PlayerController.js

Thân.
Chương.

**Comment by hohvn** [comment]
Cảm ơn bạn nhiều lắm. Mình học được rất nhiều từ project của bạn. Mình đang nghiên cứu làm 1 gảm, nếu có j thắc mắc mình sẽ hỏi. Một lần nữa cảm ơn bạn nhiều.

**Comment by rexey3s** [comment]
Không có gì đâu bạn, mình cũng  vui vì project của mình giúp được bạn :-)
